// auto-generated by scripts/import-store //
// @ts-nocheck
import useStore from "@/store/index"

export
{
    useStore,
}

declare module "@vue/runtime-core"
{
    export interface ComponentCustomProperties
    {
        store: ReturnType<typeof useStore>
    }
}
