// auto-generated by scripts/import-api //
// @ts-nocheck
import Home from "@/ui/view-home/index.vue"
import PageNotFound from "@/ui/view-page-not-found/index.vue"



export default {
    Home,
    PageNotFound,
}
