// auto-generated by scripts/import-api //
// @ts-nocheck
import Home from "@/ui/view-home/index.vue"
import Home_Tasks from "@/ui/view-home/view-tasks/index.vue"
import PageNotFound from "@/ui/view-page-not-found/index.vue"



export default {
    Home,
    Home_Tasks,
    PageNotFound,
}
